#!/bin/sh

#
## Found using sudo lsusb -t
USB_PORT="2-2"
USB_PATH="/sys/bus/usb/drivers/usb"

KillNetworking()
{
    rfkill block wifi
}

RestoreNetworking()
{
    rfkill unblock wifi
    echo "${USB_PORT}"|sudo tee "${USB_PATH}/unbind"
    sleep 1
    echo "${USB_PORT}"|sudo tee "${USB_PATH}/bind"
}

case $1 in
    hibernate)
        KillNetworking
        ;;
    suspend)
        KillNetworking
        ;;
    thaw)
        RestoreNetworking
        ;;
    resume)
        RestoreNetworking
        ;;
    *)
        echo Something is not right.
        ;;
esac
